version: "3.10"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app # Mount project directory into the container
    command: ["./start.sh"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge